[profile.default]
solc = "0.8.19"
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "safe-core-protocol/contracts/=lib/safe-core-protocol/contracts/",
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
